name: Miracle deployment

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Build distribution
        run: |
          make dist
      # - uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --cache-control max-age=30 --metadata-directive REPLACE
      #   env:
      #     AWS_S3_BUCKET: bbc.xania.org
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     SOURCE_DIR: "out/dist"
